#!/bin/bash

# Tokenization Platform - Native Setup Script
# This script sets up the platform without Docker dependencies

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
DB_NAME="tokenization_db"
DB_TEST_NAME="tokenization_test_db"
DB_USER="postgres"
DB_HOST="localhost"
DB_PORT="5432"
REDIS_PORT="6379"
API_PORT="8080"

# Banner
echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                      ║"
echo "║    🚀 TOKENIZATION PLATFORM - NATIVE SETUP                          ║"
echo "║                                                                      ║"
echo "║    Setting up without Docker - Using native PostgreSQL              ║"
echo "║                                                                      ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

# Function to print status
print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${CYAN}ℹ️  $1${NC}"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to check if PostgreSQL is running
check_postgres() {
    if pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

# Function to start PostgreSQL service
start_postgres() {
    print_status "Starting PostgreSQL service..."

    if check_postgres; then
        print_success "PostgreSQL is already running"
        return 0
    fi

    # Try different ways to start PostgreSQL
    if command_exists systemctl; then
        sudo systemctl start postgresql
        sudo systemctl enable postgresql
    elif command_exists service; then
        sudo service postgresql start
    else
        print_error "Cannot start PostgreSQL automatically. Please start it manually."
        return 1
    fi

    # Wait for PostgreSQL to be ready
    local attempts=0
    while [ $attempts -lt 30 ]; do
        if check_postgres; then
            print_success "PostgreSQL is now running"
            return 0
        fi
        attempts=$((attempts + 1))
        sleep 1
    done

    print_error "PostgreSQL failed to start within 30 seconds"
    return 1
}

# Function to setup database
setup_database() {
    print_status "Setting up databases..."

    # Get PostgreSQL version and user info
    local pg_version=$(psql --version | awk '{print $3}' | cut -d'.' -f1,2)
    print_info "PostgreSQL version: $pg_version"

    # Create main database
    print_status "Creating database: $DB_NAME"
    if sudo -u postgres createdb "$DB_NAME" 2>/dev/null; then
        print_success "Database '$DB_NAME' created"
    else
        print_info "Database '$DB_NAME' might already exist"
    fi

    # Create test database
    print_status "Creating test database: $DB_TEST_NAME"
    if sudo -u postgres createdb "$DB_TEST_NAME" 2>/dev/null; then
        print_success "Test database '$DB_TEST_NAME' created"
    else
        print_info "Test database '$DB_TEST_NAME' might already exist"
    fi

    # Set up database user permissions
    print_status "Setting up database permissions..."
    sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres123';" 2>/dev/null || true

    print_success "Database setup completed"
}

# Function to install Rust tools
install_rust_tools() {
    print_status "Installing required Rust tools..."

    # Install sqlx-cli
    if cargo install --list | grep -q "sqlx-cli"; then
        print_success "sqlx-cli already installed"
    else
        print_status "Installing sqlx-cli..."
        cargo install sqlx-cli --no-default-features --features postgres
        print_success "sqlx-cli installed"
    fi

    # Install cargo-watch (optional but useful)
    if cargo install --list | grep -q "cargo-watch"; then
        print_success "cargo-watch already installed"
    else
        print_status "Installing cargo-watch..."
        cargo install cargo-watch
        print_success "cargo-watch installed"
    fi
}

# Function to setup environment
setup_environment() {
    print_status "Setting up environment configuration..."

    # Create .env file
    if [[ -f ".env" ]]; then
        print_info ".env already exists - backing up as .env.backup"
        cp .env .env.backup
    fi

    # Create native environment file
    cat > .env << EOF
# Native Development Environment Configuration
# Generated by setup-native.sh

# =============================================================================
# Application Environment
# =============================================================================
RUST_ENV=development
RUST_LOG=debug
RUST_BACKTRACE=1

# =============================================================================
# Server Configuration
# =============================================================================
SERVER_HOST=0.0.0.0
SERVER_PORT=$API_PORT
CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:$API_PORT
MAX_CONNECTIONS=100
TIMEOUT_SECONDS=30

# =============================================================================
# Database Configuration (Native PostgreSQL)
# =============================================================================
DATABASE_URL=postgresql://postgres:postgres123@$DB_HOST:$DB_PORT/$DB_NAME
DB_MAX_CONNECTIONS=10
DB_MIN_CONNECTIONS=1
DB_CONNECTION_TIMEOUT=30
DB_IDLE_TIMEOUT=600

# =============================================================================
# JWT Configuration (Development Only!)
# =============================================================================
JWT_SECRET=native-development-jwt-secret-key-for-tokenization-platform-minimum-32-chars
JWT_EXPIRATION_HOURS=24
JWT_REFRESH_EXPIRATION_DAYS=30
JWT_ALGORITHM=HS256

# =============================================================================
# Blockchain Configuration (Mock for now)
# =============================================================================
BLOCKCHAIN_NETWORK=localhost
BLOCKCHAIN_RPC_URL=http://localhost:8545
BLOCKCHAIN_PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
BLOCKCHAIN_GAS_LIMIT=3000000
BLOCKCHAIN_GAS_PRICE=20000000000

# Smart Contract Addresses (Mock)
CONTRACT_TOKEN_FACTORY=0x0000000000000000000000000000000000000000
CONTRACT_MARKETPLACE=0x0000000000000000000000000000000000000000
CONTRACT_COMPLIANCE=0x0000000000000000000000000000000000000000
CONTRACT_STAKING=0x0000000000000000000000000000000000000000

# =============================================================================
# Development KYC & Compliance (Mock Providers)
# =============================================================================
KYC_PROVIDER=mock
KYC_API_KEY=mock-kyc-api-key-for-development
AML_PROVIDER=mock
AML_API_KEY=mock-aml-api-key-for-development
AUTO_VERIFICATION=true
VERIFICATION_TIMEOUT_HOURS=1

# =============================================================================
# Email Configuration (Local SMTP simulator)
# =============================================================================
SMTP_HOST=localhost
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
FROM_EMAIL=noreply@tokenization.local
FROM_NAME=Tokenization Platform Native

# =============================================================================
# Push Notification Configuration (Mock)
# =============================================================================
FIREBASE_KEY=mock-firebase-key-for-development
APNS_KEY=mock-apns-key-for-development
APNS_KEY_ID=mock-key-id
APNS_TEAM_ID=mock-team-id

# =============================================================================
# Redis Configuration (Optional - will use in-memory if not available)
# =============================================================================
REDIS_URL=redis://localhost:$REDIS_PORT

# =============================================================================
# Security Configuration (Development)
# =============================================================================
BCRYPT_COST=4
RATE_LIMIT_REQUESTS=1000
RATE_LIMIT_WINDOW_SECONDS=3600
SESSION_TIMEOUT_MINUTES=120
MAX_LOGIN_ATTEMPTS=10
LOCKOUT_DURATION_MINUTES=5

# =============================================================================
# File Storage Configuration (Local)
# =============================================================================
FILE_STORAGE_PATH=./storage/documents

# =============================================================================
# Development Features
# =============================================================================
ENABLE_SWAGGER_UI=true
ENABLE_DEBUG_ROUTES=true
SKIP_EMAIL_VERIFICATION=true
MOCK_BLOCKCHAIN=true
MOCK_KYC_PROVIDER=true
MOCK_EXTERNAL_APIS=true

# =============================================================================
# Test Database
# =============================================================================
TEST_DATABASE_URL=postgresql://postgres:postgres123@$DB_HOST:$DB_PORT/$DB_TEST_NAME
EOF

    print_success "Environment file created"

    # Create necessary directories
    mkdir -p storage/documents
    mkdir -p logs
    print_success "Created storage directories"
}

# Function to run database migrations
run_migrations() {
    print_status "Running database migrations..."

    export DATABASE_URL="postgresql://postgres:postgres123@$DB_HOST:$DB_PORT/$DB_NAME"

    # Run migrations
    sqlx migrate run
    print_success "Main database migrations completed"

    # Run test database migrations
    export TEST_DATABASE_URL="postgresql://postgres:postgres123@$DB_HOST:$DB_PORT/$DB_TEST_NAME"
    sqlx migrate run --database-url "$TEST_DATABASE_URL"
    print_success "Test database migrations completed"
}

# Function to seed database
seed_database() {
    print_status "Seeding database with initial data..."

    # Create seed SQL
    cat << 'EOF' | PGPASSWORD=postgres123 psql -h "$DB_HOST" -p "$DB_PORT" -U postgres -d "$DB_NAME"
-- Insert default admin user if not exists
INSERT INTO users (
    id,
    email,
    password_hash,
    first_name,
    last_name,
    username,
    role,
    status,
    email_verified,
    created_at,
    updated_at
) VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'admin@tokenization.local',
    '$2b$04$Vg4mTpjmgL5yJKxGN7hgjuqI0s7Lj9OaOgGhA4QcWRGy.EkVaEvWW', -- password: admin123
    'Platform',
    'Administrator',
    'admin',
    'active',
    true,
    NOW(),
    NOW()
) ON CONFLICT (email) DO NOTHING;

-- Insert sample investor user
INSERT INTO users (
    id,
    email,
    password_hash,
    first_name,
    last_name,
    username,
    role,
    status,
    email_verified,
    created_at,
    updated_at
) VALUES (
    'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'investor@tokenization.local',
    '$2b$04$Vg4mTpjmgL5yJKxGN7hgjuqI0s7Lj9OaOgGhA4QcWRGy.EkVaEvWW', -- password: admin123
    'John',
    'Investor',
    'investor',
    'active',
    true,
    NOW(),
    NOW()
) ON CONFLICT (email) DO NOTHING;

-- Insert sample Australian real estate project
INSERT INTO projects (
    id,
    name,
    description,
    project_type,
    status,
    owner_id,
    location,
    property_address,
    total_value,
    minimum_investment,
    maximum_investment,
    funds_raised,
    investor_count,
    expected_return,
    investment_period_months,
    property_details,
    legal_documents,
    images,
    is_tokenized,
    compliance_verified,
    kyc_required,
    created_at,
    updated_at
) VALUES (
    'c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a13',
    'Sydney CBD Premium Tower',
    'Luxury commercial development in Sydney CBD with guaranteed 8% annual returns. Prime location with major corporate tenants already secured.',
    'commercial',
    'active',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'Sydney, NSW, Australia',
    '123 George Street, Sydney NSW 2000',
    75000000,
    25000,
    500000,
    15000000,
    45,
    8.5,
    36,
    '{"property_type": "commercial", "floors": 35, "office_space": "45000 sqm", "retail_space": "5000 sqm", "parking_spaces": 200, "major_tenants": ["CommBank", "Westpac", "Law Firm Partners"], "completion_date": "2025-12-01", "architect": "Foster + Partners", "green_rating": "6 Star Green Star"}',
    '{"planning_permit", "environmental_assessment", "financial_projections"}',
    '{"exterior_render", "lobby_render", "floor_plans", "location_map"}',
    false,
    true,
    true,
    NOW(),
    NOW()
) ON CONFLICT (id) DO NOTHING;

-- Insert sample US real estate project
INSERT INTO projects (
    id,
    name,
    description,
    project_type,
    status,
    owner_id,
    location,
    property_address,
    total_value,
    minimum_investment,
    maximum_investment,
    funds_raised,
    investor_count,
    expected_return,
    investment_period_months,
    property_details,
    legal_documents,
    images,
    is_tokenized,
    compliance_verified,
    kyc_required,
    created_at,
    updated_at
) VALUES (
    'd3eebc99-9c0b-4ef8-bb6d-6bb9bd380a14',
    'Austin Tech Hub Residential',
    'Modern residential complex in Austin tech district. High demand area with strong rental yields and appreciation potential.',
    'residential',
    'pending_approval',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'Austin, TX, USA',
    '456 South Congress Ave, Austin TX 78704',
    45000000,
    15000,
    300000,
    5000000,
    22,
    12.0,
    24,
    '{"property_type": "residential", "units": 180, "unit_types": ["1BR", "2BR", "3BR", "Penthouse"], "amenities": ["Pool", "Gym", "Co-working", "Rooftop Garden"], "parking_spaces": 200, "completion_date": "2025-08-01", "target_demographic": "Tech Professionals"}',
    '{"zoning_approval", "construction_permits", "market_analysis"}',
    '{"site_plan", "unit_layouts", "amenity_renders"}',
    false,
    false,
    true,
    NOW(),
    NOW()
) ON CONFLICT (id) DO NOTHING;

-- Insert compliance profiles for users
INSERT INTO compliance_profiles (
    id,
    user_id,
    risk_rating,
    investor_type,
    accredited_investor,
    accreditation_verified,
    investment_limit,
    geographic_restrictions,
    compliance_flags,
    last_review_date,
    next_review_date,
    created_at,
    updated_at
) VALUES (
    'e4eebc99-9c0b-4ef8-bb6d-6bb9bd380a15',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'low',
    'institutional',
    true,
    true,
    50000000,
    '{}',
    '{}',
    NOW(),
    NOW() + INTERVAL '1 year',
    NOW(),
    NOW()
),
(
    'f5eebc99-9c0b-4ef8-bb6d-6bb9bd380a16',
    'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a12',
    'medium',
    'accredited',
    true,
    false,
    1000000,
    '{}',
    '{}',
    NOW(),
    NOW() + INTERVAL '1 year',
    NOW(),
    NOW()
) ON CONFLICT (user_id) DO NOTHING;

-- Insert KYC verification records
INSERT INTO kyc_verifications (
    id,
    user_id,
    verification_status,
    risk_level,
    verification_provider,
    documents_verified,
    identity_verified,
    address_verified,
    phone_verified,
    email_verified,
    pep_check,
    sanctions_check,
    adverse_media_check,
    verification_score,
    verification_date,
    created_at,
    updated_at
) VALUES (
    '10eebc99-9c0b-4ef8-bb6d-6bb9bd380a17',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'approved',
    'low',
    'internal',
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    95.0,
    NOW(),
    NOW(),
    NOW()
) ON CONFLICT (user_id) DO NOTHING;

EOF

    if [ $? -eq 0 ]; then
        print_success "Database seeded with sample data"
    else
        print_warning "Database seeding completed with some warnings"
    fi
}

# Function to build application
build_application() {
    print_status "Building Rust application..."

    # Clean build cache if needed
    if [ "$1" = "--clean" ]; then
        cargo clean
    fi

    # Build the application
    cargo build
    print_success "Application built successfully"
}

# Function to check system resources
check_system_resources() {
    print_status "Checking system resources..."

    # Check available memory
    local mem_total=$(grep MemTotal /proc/meminfo | awk '{print int($2/1024)}')
    local mem_available=$(grep MemAvailable /proc/meminfo | awk '{print int($2/1024)}')

    print_info "Memory: ${mem_available}MB available / ${mem_total}MB total"

    if [ "$mem_available" -lt 1024 ]; then
        print_warning "Low available memory. Consider closing other applications."
    fi

    # Check disk space
    local disk_available=$(df . | awk 'NR==2 {print int($4/1024)}')
    print_info "Disk space: ${disk_available}MB available"

    if [ "$disk_available" -lt 2048 ]; then
        print_warning "Low disk space. Consider freeing up space."
    fi
}

# Function to display final information
display_final_info() {
    echo ""
    echo -e "${PURPLE}╔══════════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${PURPLE}║                   🎉 NATIVE SETUP COMPLETE!                         ║${NC}"
    echo -e "${PURPLE}╚══════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${GREEN}Your Tokenization Platform is ready for native development!${NC}"
    echo ""
    echo -e "${CYAN}🌐 Application Access:${NC}"
    echo -e "   • API Server: Will run on ${YELLOW}http://localhost:$API_PORT${NC}"
    echo -e "   • Health Check: ${YELLOW}http://localhost:$API_PORT/health${NC}"
    echo -e "   • API Documentation: ${YELLOW}http://localhost:$API_PORT/docs${NC}"
    echo ""
    echo -e "${CYAN}🗄️  Database Information:${NC}"
    echo -e "   • PostgreSQL: ${YELLOW}localhost:$DB_PORT${NC}"
    echo -e "   • Database: ${YELLOW}$DB_NAME${NC}"
    echo -e "   • Username: ${YELLOW}postgres${NC}"
    echo -e "   • Password: ${YELLOW}postgres123${NC}"
    echo ""
    echo -e "${CYAN}👤 Test Accounts:${NC}"
    echo -e "   • Admin: ${YELLOW}admin@tokenization.local${NC} / ${YELLOW}admin123${NC}"
    echo -e "   • Investor: ${YELLOW}investor@tokenization.local${NC} / ${YELLOW}admin123${NC}"
    echo ""
    echo -e "${CYAN}🏢 Sample Projects Loaded:${NC}"
    echo -e "   • Sydney CBD Premium Tower (${YELLOW}\$75M Commercial${NC})"
    echo -e "   • Austin Tech Hub Residential (${YELLOW}\$45M Residential${NC})"
    echo ""
    echo -e "${GREEN}🚀 Start Your Platform:${NC}"
    echo -e "   ${BLUE}cargo run${NC}                     # Start the API server"
    echo -e "   ${BLUE}cargo watch -x run${NC}           # Start with auto-reload"
    echo -e "   ${BLUE}cargo test${NC}                    # Run tests"
    echo ""
    echo -e "${GREEN}📊 Quick API Tests:${NC}"
    echo -e "   ${BLUE}curl http://localhost:$API_PORT/health${NC}"
    echo -e "   ${BLUE}curl http://localhost:$API_PORT/api/projects${NC}"
    echo ""
    echo -e "${GREEN}🔧 Development Commands:${NC}"
    echo -e "   ${BLUE}psql -h localhost -U postgres -d $DB_NAME${NC}  # Access database"
    echo -e "   ${BLUE}sqlx migrate run${NC}                             # Run new migrations"
    echo -e "   ${BLUE}cargo clippy${NC}                                 # Code linting"
    echo -e "   ${BLUE}cargo fmt${NC}                                    # Code formatting"
    echo ""
}

# Function to run health check
health_check() {
    print_status "Running system health check..."

    # Check PostgreSQL
    if check_postgres; then
        print_success "PostgreSQL is accessible"
    else
        print_error "PostgreSQL is not accessible"
        return 1
    fi

    # Check database exists
    if PGPASSWORD=postgres123 psql -h "$DB_HOST" -U postgres -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
        print_success "Database '$DB_NAME' exists"
    else
        print_error "Database '$DB_NAME' not found"
        return 1
    fi

    # Check if we can build
    if cargo check >/dev/null 2>&1; then
        print_success "Rust code compiles successfully"
    else
        print_error "Rust compilation issues found"
        return 1
    fi

    print_success "Health check passed!"
}

# Main execution
main() {
    print_status "Starting native setup for Tokenization Platform"

    # Check system resources
    check_system_resources

    # Step 1: Start PostgreSQL
    start_postgres

    # Step 2: Install Rust tools
    install_rust_tools

    # Step 3: Setup environment
    setup_environment

    # Step 4: Setup database
    setup_database

    # Step 5: Run migrations
    run_migrations

    # Step 6: Seed database
    seed_database

    # Step 7: Build application
    build_application

    # Step 8: Health check
    health_check

    # Step 9: Display final information
    display_final_info

    print_success "Native setup completed successfully!"
    echo ""
    echo -e "${GREEN}Ready to launch! Run: ${BLUE}cargo run${NC}"
}

# Error handling
trap 'print_error "Setup failed. Check the error messages above."' ERR

# Handle command line arguments
case "${1:-}" in
    --help|-h)
        echo "Usage: $0 [options]"
        echo ""
        echo "Options:"
        echo "  --help, -h          Show this help message"
        echo "  --clean             Clean build cache before setup"
        echo "  --check-only        Run health check only"
        echo ""
        echo "This script sets up the Tokenization Platform using native"
        echo "PostgreSQL installation (no Docker required)."
        exit 0
        ;;
    --clean)
        print_info "Clean build requested"
        main --clean
        ;;
    --check-only)
        health_check
        exit 0
        ;;
    *)
        main "$@"
        ;;
esac
