// src/database/wallet_queries.rs
use sqlx::{PgPool, Row};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[derive(Debug, Clone)]
pub struct WalletUser {
    pub id: Uuid,
    pub email: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub username: String,
    pub role: String,
    pub wallet_address: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

// Find user by wallet address
pub async fn find_user_by_wallet(
    pool: &PgPool,
    wallet_address: &str,
) -> Result<Option<WalletUser>, sqlx::Error> {
    let row = sqlx::query(
        r#"
        SELECT
          id,
          email,
          first_name,
          last_name,
          username,
          role::text,  -- Cast to text
          wallet_address,
          created_at,
          updated_at
        FROM users
        WHERE wallet_address = $1
        "#
    )
    .bind(wallet_address.to_lowercase())
    .fetch_optional(pool)
    .await?;

    match row {
        Some(row) => Ok(Some(WalletUser {
            id: row.get("id"),
            email: row.get("email"),
            first_name: row.get("first_name"),
            last_name: row.get("last_name"),
            username: row.get("username"),
            role: row.get("role"),  // Now this will work
            wallet_address: row.get("wallet_address"),
            created_at: row.get("created_at"),
            updated_at: row.get("updated_at"),
        })),
        None => Ok(None),
    }
}



use crate::models::UserRole; // already generated by sqlx

pub async fn create_wallet_user(
    pool: &PgPool,
    wallet_address: &str,
) -> Result<WalletUser, sqlx::Error> {
    let user_id = Uuid::new_v4();
    let username = format!("wallet_{}", &wallet_address[2..10].to_lowercase());
    let now = Utc::now();
    let email = format!("{}@wallet.tokenization.local", &wallet_address[2..10]);
    let dummy_password_hash = "$2b$12$dummy_hash_for_wallet_users_only";

    let row = sqlx::query(
        r#"
        INSERT INTO users (
            id, 
            email,  
            username, 
            wallet_address, 
            role,
            password_hash,    -- Add this column
            created_at,
            updated_at
        ) 
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8)  -- Now 8 parameters
        RETURNING 
            id, 
            email, 
            first_name, 
            last_name, 
            username, 
            role::text as role, 
            wallet_address,
            created_at,
            updated_at
        "#
    )
    .bind(user_id)                          // $1: id
    .bind(&email)                           // $2: email
    .bind(&username)                        // $3: username
    .bind(wallet_address.to_lowercase())    // $4: wallet_address
    .bind(UserRole::User)                   // $5: role
    .bind(dummy_password_hash)              // $6: password_hash
    .bind(now)                              // $7: created_at
    .bind(now)                              // $8: updated_at
    .fetch_one(pool)
    .await?;

    Ok(WalletUser {
        id: row.get("id"),
        email: row.get("email"),
        first_name: row.get("first_name"),
        last_name: row.get("last_name"),
        username: row.get("username"),
        role: row.get("role"),
        wallet_address: row.get("wallet_address"),
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
    })
}
// Find or create wallet user (combines the above)
pub async fn find_or_create_wallet_user(
    pool: &PgPool,
    wallet_address: &str,
) -> Result<WalletUser, sqlx::Error> {
    // First try to find existing user
    if let Some(user) = find_user_by_wallet(pool, wallet_address).await? {
        return Ok(user);
    }

    // If not found, create new user
    create_wallet_user(pool, wallet_address).await
}

// Update user's last login time
pub async fn update_wallet_login_time(
    pool: &PgPool,
    user_id: Uuid,
) -> Result<(), sqlx::Error> {
    sqlx::query(
        r#"
        UPDATE users 
        SET 
            updated_at = $1,
            last_login = $1
        WHERE id = $2
        "#
    )
    .bind(Utc::now())
    .bind(user_id)
    .execute(pool)
    .await?;

    Ok(())
}

// Check if wallet address is already in use
pub async fn wallet_address_exists(
    pool: &PgPool,
    wallet_address: &str,
) -> Result<bool, sqlx::Error> {
    let row = sqlx::query(
        "SELECT COUNT(*) as count FROM users WHERE wallet_address = $1"
    )
    .bind(wallet_address.to_lowercase())
    .fetch_one(pool)
    .await?;

    let count: i64 = row.get("count");
    Ok(count > 0)
}

// Link wallet to existing email user
pub async fn link_wallet_to_user(
    pool: &PgPool,
    user_id: Uuid,
    wallet_address: &str,
) -> Result<WalletUser, sqlx::Error> {
    let row = sqlx::query(
        r#"
        UPDATE users 
        SET 
            wallet_address = $1,
            updated_at = $2
        WHERE id = $3
        RETURNING 
            id, 
            email, 
            first_name, 
            last_name, 
            username, 
            role,
            wallet_address,
            created_at,
            updated_at
        "#
    )
    .bind(wallet_address.to_lowercase())
    .bind(Utc::now())
    .bind(user_id)
    .fetch_one(pool)
    .await?;

    Ok(WalletUser {
        id: row.get("id"),
        email: row.get("email"),
        first_name: row.get("first_name"),
        last_name: row.get("last_name"),
        username: row.get("username"),
        role: row.get("role"), 
        wallet_address: row.get("wallet_address"),
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
    })
}

// Remove wallet from user (for disconnecting)
pub async fn unlink_wallet_from_user(
    pool: &PgPool,
    user_id: Uuid,
) -> Result<(), sqlx::Error> {
    sqlx::query(
        r#"
        UPDATE users 
        SET 
            wallet_address = NULL,
            updated_at = $1
        WHERE id = $2
        "#
    )
    .bind(Utc::now())
    .bind(user_id)
    .execute(pool)
    .await?;

    Ok(())
}

// #[cfg(test)]
// mod tests {
//     use super::*;
//     // Add your test database connection setup here
    
//     #[tokio::test]
//     async fn test_wallet_user_creation() {
//         // This would require a test database setup
//         // You can implement this based on your existing test patterns
//     }
// }
